// <auto-generated />
using System;
using ExpensesManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpensesManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250413160919_UpdateSeeds")]
    partial class UpdateSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpensesManager.Models.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorHex = "#D20103",
                            Description = "",
                            Name = "Food"
                        },
                        new
                        {
                            Id = 2,
                            ColorHex = "#FE9900",
                            Description = "",
                            Name = "Bills"
                        },
                        new
                        {
                            Id = 3,
                            ColorHex = "#060270",
                            Description = "",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 4,
                            ColorHex = "#98F5F9",
                            Description = "",
                            Name = "Entertainment"
                        });
                });

            modelBuilder.Entity("ExpensesManager.Models.ExpenseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 12.99m,
                            CategoryId = 1,
                            Date = new DateOnly(2025, 1, 1),
                            Name = "Joghurt"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 11.50m,
                            CategoryId = 1,
                            Date = new DateOnly(2025, 1, 2),
                            Name = "Mega Rollo Kebab"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 193.12m,
                            CategoryId = 2,
                            Date = new DateOnly(2025, 1, 3),
                            Name = "Electricity"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 32.99m,
                            CategoryId = 2,
                            Date = new DateOnly(2025, 1, 4),
                            Name = "Phone bill"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 99.99m,
                            CategoryId = 3,
                            Date = new DateOnly(2025, 1, 5),
                            Name = "T-Shirt"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 139.99m,
                            CategoryId = 3,
                            Date = new DateOnly(2025, 1, 6),
                            Name = "Hoodie"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 29.99m,
                            CategoryId = 4,
                            Date = new DateOnly(2025, 1, 7),
                            Name = "Movie theater"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 12m,
                            CategoryId = 4,
                            Date = new DateOnly(2025, 1, 8),
                            Name = "Ice skating"
                        });
                });

            modelBuilder.Entity("ExpensesManager.Models.ExpenseEntity", b =>
                {
                    b.HasOne("ExpensesManager.Models.CategoryEntity", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ExpensesManager.Models.CategoryEntity", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
